### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by martinschorb** [mobie-org/covid-em-datasets#3]
Hi,

I am trying to push a new branch to add new data and fix the local repo.

```
Password for 'https://martinschorb@github.com': 
remote: Permission to mobie-org/covid-em-datasets.git denied to martinschorb.
fatal: unable to access 'https://github.com/mobie-org/covid-em-datasets/': The requested URL returned error: 403
```

**Comment by martinschorb** [comment]
OK, trying to do the merge locally and then commit to master...

```
git commit -am 'new data'
error: insufficient permission for adding an object to repository database .git/objects
error: insufficient permission for adding an object to repository database .git/objects
error: Error building trees
```

**Comment by martinschorb** [comment]
@constantinpape 
Any news? The datasets are still screwed and I cannot update them...

**Comment by constantinpape** [comment]
Oh sorry, I didn't see this one. Give me a second, I will check.

**Comment by martinschorb** [comment]
OK, pushing should be sorted.
Could you check the local dir?
I have looked at file permissions but cannot spot any problem here.
Can you maybe commit the changes and check what we need to manually update to incorporate the new datasets?

**Comment by constantinpape** [comment]
Ok, I have pushed. I will update the data layout now.
@martinschorb have you uploaded it to s3 already?

**Comment by constantinpape** [comment]
ok, I have updated everything in the dataset and it should work, but I couldn't test it yet, because the dataset is not on s3 yet, and I can't pull to the git repo on the emcf share due to permission issues, so I also can't test it locally.
@martinschorb Could you use your sudo rights to chmod everything to `g+rwx` in the folder?

**Comment by martinschorb** [comment]
I can't... even though I am member of the group.
We need to involve IT.

**Comment by martinschorb** [comment]
should I pull?
I think that worked yesterday...

**Comment by constantinpape** [comment]
Yes, please pull.
Then I can check if it worked locally

**Comment by martinschorb** [comment]
That's the master...

```
$ git pull
Updating 436a66e..69d9a6e
Fast-forward
 data/Covid19-S4-cell1plus_5nm/images/images.json                                           | 12 +++++++-----
 data/Covid19-S4-cell1plus_5nm/images/remote/sbem-6dpf-1-whole-raw.xml                      |  1 +
 data/Covid19-S4-cell1plus_5nm/misc/bookmarks/default.json                                  | 12 ++++++++++++
 data/Covid19-S4-cell1plus_5nm/misc/{bookmarks.json => bookmarks/manuscript_bookmarks.json} |  0
 data/datasets.json                                                                         |  5 +++--
 5 files changed, 23 insertions(+), 7 deletions(-)
 create mode 100644 data/Covid19-S4-cell1plus_5nm/misc/bookmarks/default.json
 rename data/Covid19-S4-cell1plus_5nm/misc/{bookmarks.json => bookmarks/manuscript_bookmarks.json} (100%)
```

**Comment by constantinpape** [comment]
Yes, it works now:
![Screenshot from 2020-06-03 11-06-41](https://user-images.githubusercontent.com/4263537/83618192-619d7380-a58a-11ea-9806-c80e3a10f1e5.png)

But there is still an issue with the resolution: it's set to 5 micrometer instead of 5 nanometer, see
https://github.com/mobie-org/covid-em-datasets/blob/master/data/Covid19-S4-cell1plus_5nm/images/local/sbem-6dpf-1-whole-raw.xml#L20
This needs to be changed in 3 different files:
- https://github.com/mobie-org/covid-em-datasets/blob/master/data/Covid19-S4-cell1plus_5nm/images/local/sbem-6dpf-1-whole-raw.xml
- https://github.com/mobie-org/covid-em-datasets/blob/master/data/Covid19-S4-cell1plus_5nm/images/remote/sbem-6dpf-1-whole-raw.xml
- /g/emcf/common/5792_Sars-Cov-2/covid-em/data/Covid19-S4-cell1plus_5nm/images/local/sbem-6dpf-1-whole-raw.n5/setup0/timepoint0/attributes.json

For the xmls, it needs to be changed in the voxel size and in the affine.

**Comment by martinschorb** [comment]
Yes, that was the int/float type check in the converter's parameters. Ichacnged the code but not the command line call when I launched the script ;-)

Will do the changes and then upload to s3 and push the changes.
